# 'bundle exec jekyll serve'

# Theme Settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark

# Site Settings
locale: "en-US"
title: "I'm Tien"
description: "Le Minh Tien"
words_per_minute: 150
search: true
search_full_content: true

# Build settings
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Outputting
permalink: /:categories/:title/
paginate: 11 # amount of posts to show
paginate_path: /page:num/
timezone: "Asia/Singapore" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Reading Files
include:
  - _pages

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-archives

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

author:
  name: "Tien Le"
  avatar: "/assets/images/bio-photo.png"
  bio: "-> curiosity, exploration { puts \"#{curiosity} and #{exploration}\" }.('Live with passion', 'code with love')"
  location: "Singapore"
  uri: "http://lmtien.com"
  email: "dev@imtien.com"
  linkedin: "lmtien"
  github: "lmtien"

footer:
  links:
    - label: "Wanna hire me?"
      icon: "fas fa-user-secret"
      url: "https://hire.imtien.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      classes: wide
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
